### ISSUE TITLE
Matched Filter for Manchester Coding

### ISSUE THREAD

**Issue by bemasher** [denglend/decode345#1]
Have you looked at implementing a matched filter to handle the manchester coding in signal processing rather than after you've done bit-decision? You can avoid having to set any kind of signal strength thresholds if you design it a particular way.

Description of signal processing:
http://bemasher.net/rtlamr/signal.html

Matched Filter for Manchester Coding:
https://github.com/bemasher/rtlamr/blob/master/decode/decode.go#L223

**Comment by denglend** [comment]
I hadn't, so thanks for the tip.  And thanks for documenting how you approached the signal processing.
