### ISSUE TITLE
Practical Usage

### ISSUE THREAD

**Issue by kevinfealey** [denglend/decode345#6]
Thank you again for this project @denglend - you certainly saved me a lot of money by allowing me to re-use existing sensors, so I really appreciate all the work you've done to get this project to its current state!

I now have your tools (slightly modified, which I'll contribute back) running on my network, but I'm struggling to figure out my next steps..

The workflow should be, leave receive345.py and decode345 running 24/7 and reporting events via MQTT, which are picked up by some system (maybe OpenHAB, I'm not that far yet). The trouble I'm running into is that decode345 is not a constantly running service. It executes, grabs all the data from receive345, then needs to be re-run to capture new events. But when you re-run it, it grabs all old events too, and publishes them to MQTT. 

I've had a few ideas for how to resolve this, but they are all fairly complex.. some examples:

- have receive345.py publish directly to MQTT, then have decode345 listening, decoding, and pubbing back;
- have  something continuously executing decode345 and adding something along the chain to detect and drop old events;
- modify decode345 to re-open the fifo stream when it reaches the end and somehow recognize which events its already seen;

Since you've already implemented this, I'm curious how you resolved the issue of publishing all events to MQTT only once.. Is there a way to have decode345 running continuously and see updates to the fifo stream?

**Comment by denglend** [comment]
In my implementation, decode345 is running constantly.  It continues to run so long as the FIFO is open, and the FIFO remains open as long as receive345 is running.

If decode345 is terminating, that's probably an indication that something is going wrong.

**Comment by kevinfealey** [comment]
Ah, thanks @denglend - that's great to know. Both decode345.py and decode exit for me when they reach the end of the current FIFO content. I'm not sure if that is due to a difference in how our OS's handle FIFO or something else. 

Ultimately, if I remove the break on line 144 of decode345.c, the functionality is what I'm looking for. It's not elegant to remove the line though, because then the client does not exist when the FIFO is closed by receive345.py. For now, I'm going to just remove the line though and work on my remaining implementation. I may come back and try to resolve this later.

As an aside, I've been putting together a set of scripts to quickly spin up my environment in a VM. I'm using Vagrant (https://www.vagrantup.com/) to automate the VM management. I'll provide those scripts back to you as a pull request once I get this cleaned up (just a few days hopefully), so hopefully others who aren't proficient with Linux, C, and/or Python can get up and running with your toolset very quickly. It'll also hopefully allow you to more easily reproduce the issue I'm having, in case you're inclined to work on it later too.
